# Generated by Django 3.0.3 on 2020-02-25 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Verification_Code', models.CharField(max_length=200)),
                ('MSP_University', models.CharField(max_length=200)),
                ('Event_Name', models.CharField(max_length=200)),
                ('Attendee_First_Name', models.CharField(max_length=200)),
                ('Attendee_University_Name', models.CharField(max_length=200)),
            ],
        ),
    ]
