# Generated by Django 3.0.3 on 2020-02-27 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aihacks', '0002_detail_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='Attendee_First_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Attendee_University_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Email',
            field=models.EmailField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Event_Name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='MSP_University',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='detail',
            name='Verification_Code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
